### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#18]
Linda and I reviewed the Menu Bar, and changed the organization of it. Sending a pdf.file, so you can see what we have in mind.  
Note:  I need to know how to change the Menu Bar, especially the subcategories, as they may change or there will certainly be additional subcategories over time.

**Comment by megandalster** [comment]
I made the changes you suggested.  Each item on the menu bar corresponds to a page on the site.  

To edit the Menu Bar, select Appearance -> Menus on the left.  That will show page with two lists: a list of all the site's pages on the left and a list of all the items on the current menu bar on the right.

To add a page to the menu bar, just select it in the left-hand list and hit "Add to Menu".  It will appear at the bottom of the right-hand list, so you can then drag it up to the place on the menu bar where you want it to appear.  To remove a page from the menu bar, select it and hit "Remove."

When you're done making these changes, hit "Save Menu" at the top.  Now browse to the site and check that your menu bar changes are there.

I'll write this up as an instruction if you think that would be useful.  Otherwise, we can just walk through it so that you can be comfortable with it.
