### ISSUE TITLE
What I design is not what I get

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#25]
It is our understanding that we will add content to the various pages as editors.  When I created the Quilt Show content, I created spacing between the lines, so it would be easier to read.  This spacing does not translate to the Quilt Show page.  

We need what we design, be it font, color, line spacing, etc, to be what shows up on the web page we are designing.

**Comment by megandalster** [comment]
In general, a web page is not a static 8-1/2x11 document -- it must be flexible to adapt to the size of the device (iPhone, tablet, laptop, desktop) that the viewer is using.  So designing a web page needs to be flexible too.  Many of the tools you are used to with the Newsletter have direct counterparts on the web site (font styles, sizes, colors, etc.) but some do not (line spacing, for instance).  

Let's plan to talk about the Quilt Show page and go over some of the tools that are available for editing that page, so that you can begin to exploit them better.
